name: Static analysis

on:
  push:
  pull_request:

jobs:
  yaml:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: pip3 install pykwalify yamllint
      - run: pykwalify --data-file games.yaml --schema-file schema.yaml
      - run: yamllint games.yaml
